# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0120487018b2fba2d1893f1a5adf27809dc500ad8c9820525e07b4e5d07c169233d3dd5af91d6a399237856dc26f179b5644ef0a759da21740ee95417b65bdb7

test:
  secret_key_base: 871ad8d1d0ef09d9bc75c2035bfc080eb2dd99835b4c09c6c15b9c3582a8c672e2f9afc3a4d400a6ab0e5abf53d05c6e32081e1ae2a798fca217dd46e18bb3db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
